### ISSUE TITLE
Get, Create, Update Real  data 

### ISSUE THREAD

**Issue by DininduKanchana** [ChamikaraTDP/NewNest#3]
[real-data.txt](https://github.com/ChamikaraTDP/NewNest/files/5321906/real-data.txt)

Now we are going to save the real data to the DB. Plz, refer to the attached text file. This is a sample object that needs to be saved.

`tabbedContainer1` is a dynamic id so that will be changed in every object. Consider about it.
in `tabs` the keys "1", "2" are also dynamic values..

In the update call assume we send the whole object with updated values from the frontend.

**Comment by DininduKanchana** [comment]
Db schema is  updated like below..
Now tabberContainerId is removed.
![db](https://user-images.githubusercontent.com/13985019/95095570-d525dc00-0748-11eb-903d-3e0a40e4759d.png)

**Comment by ChamikaraTDP** [comment]
I have completed it. Please recheck.
